"""add_reranker_fields_to_batch_test_sessions

Revision ID: bfc4c1885c2e
Revises: c4899c361b85
Create Date: 2026-01-25 09:03:00.940409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfc4c1885c2e'
down_revision: Union[str, None] = 'c4899c361b85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('batch_test_sessions', sa.Column('reranker_used', sa.Boolean(), nullable=True))
    op.add_column('batch_test_sessions', sa.Column('reranker_provider', sa.String(length=50), nullable=True))
    op.add_column('batch_test_sessions', sa.Column('reranker_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if columns exist before dropping them
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [col['name'] for col in inspector.get_columns('batch_test_sessions')]
    
    if 'reranker_model' in columns:
        op.drop_column('batch_test_sessions', 'reranker_model')
    if 'reranker_provider' in columns:
        op.drop_column('batch_test_sessions', 'reranker_provider')
    if 'reranker_used' in columns:
        op.drop_column('batch_test_sessions', 'reranker_used')
    # ### end Alembic commands ###
