"""add_search_and_reranker_to_semantic_similarity

Revision ID: 305b5391cb41
Revises: 20260203_230511
Create Date: 2026-02-04 11:21:20.718971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '305b5391cb41'
down_revision: Union[str, None] = '20260203_230511'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('course_prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint(op.f('uq_course_prompt_templates_course_id_name'), 'course_prompt_templates', type_='unique')
    op.create_index(op.f('ix_course_prompt_templates_id'), 'course_prompt_templates', ['id'], unique=False)
    op.add_column('semantic_similarity_results', sa.Column('search_top_k', sa.Integer(), nullable=True))
    op.add_column('semantic_similarity_results', sa.Column('search_alpha', sa.Float(), nullable=True))
    op.add_column('semantic_similarity_results', sa.Column('reranker_used', sa.Boolean(), nullable=True))
    op.add_column('semantic_similarity_results', sa.Column('reranker_provider', sa.String(length=50), nullable=True))
    op.add_column('semantic_similarity_results', sa.Column('reranker_model', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('semantic_similarity_results', 'reranker_model')
    op.drop_column('semantic_similarity_results', 'reranker_provider')
    op.drop_column('semantic_similarity_results', 'reranker_used')
    op.drop_column('semantic_similarity_results', 'search_alpha')
    op.drop_column('semantic_similarity_results', 'search_top_k')
    op.drop_index(op.f('ix_course_prompt_templates_id'), table_name='course_prompt_templates')
    op.create_unique_constraint(op.f('uq_course_prompt_templates_course_id_name'), 'course_prompt_templates', ['course_id', 'name'], postgresql_nulls_not_distinct=False)
    op.alter_column('course_prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('course_prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    # ### end Alembic commands ###
